apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autovpaconfigs.autoscaling.k8s.io
  annotations:
    api-approved.kubernetes.io: "unapproved"
spec:
  group: autoscaling.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                excludedDeployments:
                  type: array
                  items:
                    type: string
                resourcePolicy:
                  type: object
                  properties:
                    mode:
                      type: string
                      enum:
                        - "Auto"
                        - "Off"
                    minAllowed:
                      type: object
                    maxAllowed:
                      type: object
                    controlledValues:
                      type: string
                      enum: ["RequestsAndLimits", "RequestsOnly"]
                    controlledResources:
                      type: array
                      items:
                        type: string
                        enum: [ "cpu", "memory" ]
                updatePolicy:
                  type: object
                  properties:
                    minReplicas:
                      type: integer
                    updateMode:
                      type: string
                      enum:
                        - "Auto"
                        - "Off"
                        - "Initial"
                        - "Recreate"
  scope: Namespaced
  names:
    plural: autovpaconfigs
    singular: autovpaconfig
    kind: AutoVPA
    shortNames:
      - autovpa
